"""auto-increment

Revision ID: c1460407e5a4
Revises: 736f7b2c78aa
Create Date: 2019-11-15 12:38:07.037530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1460407e5a4'
down_revision = '736f7b2c78aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_review_overall'), 'review', ['overall'], unique=False)
    op.create_index(op.f('ix_review_reviewText'), 'review', ['reviewText'], unique=False)
    op.create_index(op.f('ix_review_summary'), 'review', ['summary'], unique=False)
    op.create_index(op.f('ix_review_unixReviewTime'), 'review', ['unixReviewTime'], unique=False)
    op.drop_index('ix_review_id', table_name='review')
    op.create_index(op.f('ix_reviewer_information_reviewerName'), 'reviewer_information', ['reviewerName'], unique=False)
    op.drop_index('ix_reviewer_information_id', table_name='reviewer_information')
    op.create_index(op.f('ix_reviewer_reviews_asin'), 'reviewer_reviews', ['asin'], unique=False)
    op.drop_index('ix_reviewer_reviews_id', table_name='reviewer_reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviewer_reviews_id', 'reviewer_reviews', ['id'], unique=False)
    op.drop_index(op.f('ix_reviewer_reviews_asin'), table_name='reviewer_reviews')
    op.create_index('ix_reviewer_information_id', 'reviewer_information', ['id'], unique=False)
    op.drop_index(op.f('ix_reviewer_information_reviewerName'), table_name='reviewer_information')
    op.create_index('ix_review_id', 'review', ['id'], unique=False)
    op.drop_index(op.f('ix_review_unixReviewTime'), table_name='review')
    op.drop_index(op.f('ix_review_summary'), table_name='review')
    op.drop_index(op.f('ix_review_reviewText'), table_name='review')
    op.drop_index(op.f('ix_review_overall'), table_name='review')
    # ### end Alembic commands ###
